language: node_js
os: linux

node_js:
  - 14

cache:
    directories:
      - node_modules
      - ~/.npm

git:
  depth: 3

install:
  - npm install

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: coverage
      script: npm run coverage